#!/bin/bash
termuxBin=/data/data/com.termux/usr/bin
echo "This software is covered by GNU GPL v3.0"
echo "A copy of the license can be found at http://www.gnu.org/licenses/gpl-3.0.en.html#content "
echo ""
function mkCmdGlobal {
        if [ $differFileNameYN == "n" ] || [ $differFileNameYN == "no" ] || [ $differFileNameYN == "N" ] || [ $differFileNameYN == "No" ]
                then
                echo "Moving $fileName to $termuxBin."
                cp $fileName $termuxBin/$fileName
                echo "Making $fileName executable."
                chmod 755 $termuxBin/$fileName
        else
                echo "Please enter the new file name."
                read newFileName
                echo "Copying $fileName to $termuxBin/$newFileName"
                cp $fileName $termuxBin/$newFileName
                echo "Making $newFileName executable." 
                chmod 755 $termuxBin/$newFileName
        fi
}
function mkCmdLocal {
        if [ $differFileNameYN == "n" ] || [ $differFileNameYN == "no" ] || [ $differFileNameYN == "N" ] || [ $differFileNameYN == "No" ]
                then
                echo "Moving $fileName to ~/bin"
                cp $fileName ~/bin/$fileName
                echo "Making $fileName executable."
                chmod 755 ~/bin/$fileName
        else
                echo "Please enter the new file name."
                read newFileName
                echo "Copying $fileName to ~/bin/$newFileName"
                cp $fileName ~/bin/$newFileName
                echo "Making $newFileName executable." 
                chmod 755 ~/bin/$newFileName
        fi
}
echo "Please enter the filename that you would like to make a command."
read fileName
echo "Do you want the command to differ from the file name? [Y/N]"
read differFileNameYN
echo "Do you want the command to be System wide? [Y/N] (No will install it for the user only)"
read sysOrUsr
if [ $sysOrUsr == "Y" ] || [ $sysOrUsr == "y" ] || [ $sysOrUsr == "Yes" ] || [ $sysOrUsr == "yes" ]
        then
	mkCmdGlobal
        else
	mkCmdLocal
fi
echo "Do you want to keep a copy of the file?"
read keepOldFile
if [ $keepOldFile == "n" ] || [ $keepOldFile == "no" ] || [ $keepOldFile == "N" ] || [ $keepOldFile == "No" ]
	then
	rm $fileName
fi
